# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newDetailSecondrowdata.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
# 2018/4/8
# version 2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QTableWidget,QGridLayout,QWidget ,QHBoxLayout , QPushButton,QHeaderView,QAbstractItemView,QFrame
from Parse.Multithread.Threerowsdata import Threerowsdata

class Ui_Form(QTableWidget):
    def __init__(self,parent = None):
        super(Ui_Form, self).__init__(parent)
        self.resize(784, 754)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
#        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "frame"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "1-Interface id"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "2-Arrival time"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Form", "3-timeshift"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Form", "4-Epoch time"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("Form", "5-time delta from captured frame"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("Form", "6-time delta from displayed frame"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("Form", "7-time since reference or first frame"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("Form", "8-frame number"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("Form", "9-frame length"))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("Form", "11-capture length"))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("Form", "12-frame is marked"))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("Form", "13-frame is ignored"))
        self.treeWidget.topLevelItem(0).child(12).setText(0, _translate("Form", "14-protocol in frame:"))
        self.treeWidget.topLevelItem(0).child(13).setText(0, _translate("Form", "15-color rule name"))
        self.treeWidget.topLevelItem(0).child(14).setText(0, _translate("Form", "16-color rule string"))
        self.treeWidget.topLevelItem(0).child(15).setText(0, _translate("Form", "Interface name"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "ethernet "))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "destination"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "address (hard device)"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "source "))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("Form", "address(hard device)"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("Form", "type"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "PPPOE"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Form", "version:"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Form", "type"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Form", "session id"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Form", "payload length"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Form", "p2p"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("Form", "protocol"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Form", "ip"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Form", "version"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Form", "header length"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Form", "different service field"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("Form", "different services codepoint"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("Form", "explicit congestion notification"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("Form", "total length"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("Form", "identification"))
        self.treeWidget.topLevelItem(4).child(7).setText(0, _translate("Form", "flags"))
        self.treeWidget.topLevelItem(4).child(8).setText(0, _translate("Form", "reverse bit"))
        self.treeWidget.topLevelItem(4).child(9).setText(0, _translate("Form", "dont fragment"))
        self.treeWidget.topLevelItem(4).child(10).setText(0, _translate("Form", "more fragment"))
        self.treeWidget.topLevelItem(4).child(11).setText(0, _translate("Form", "fragment offset"))
        self.treeWidget.topLevelItem(4).child(12).setText(0, _translate("Form", "time to live"))
        self.treeWidget.topLevelItem(4).child(13).setText(0, _translate("Form", "protocol"))
        self.treeWidget.topLevelItem(4).child(14).setText(0, _translate("Form", "header checksum"))
        self.treeWidget.topLevelItem(4).child(15).setText(0, _translate("Form", "header checksum status"))
        self.treeWidget.topLevelItem(4).child(16).setText(0, _translate("Form", "source "))
        self.treeWidget.topLevelItem(4).child(17).setText(0, _translate("Form", "destination"))
        self.treeWidget.topLevelItem(4).child(18).setText(0, _translate("Form", "source geoip"))
        self.treeWidget.topLevelItem(4).child(19).setText(0, _translate("Form", "destinatoin geoip"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Form", "tcp"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Form", "source port"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Form", "destination port"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("Form", "stream index"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("Form", "tcp segment"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("Form", "sequence number"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("Form", "ACK"))
        self.treeWidget.topLevelItem(5).child(6).setText(0, _translate("Form", "header length"))
        self.treeWidget.topLevelItem(5).child(7).setText(0, _translate("Form", "flags"))
        self.treeWidget.topLevelItem(5).child(8).setText(0, _translate("Form", "reversed"))
        self.treeWidget.topLevelItem(5).child(9).setText(0, _translate("Form", "nonce"))
        self.treeWidget.topLevelItem(5).child(10).setText(0, _translate("Form", "congestion"))
        self.treeWidget.topLevelItem(5).child(11).setText(0, _translate("Form", "ecn echo"))
        self.treeWidget.topLevelItem(5).child(12).setText(0, _translate("Form", "urgent"))
        self.treeWidget.topLevelItem(5).child(13).setText(0, _translate("Form", "ack"))
        self.treeWidget.topLevelItem(5).child(14).setText(0, _translate("Form", "push"))
        self.treeWidget.topLevelItem(5).child(15).setText(0, _translate("Form", "reset"))
        self.treeWidget.topLevelItem(5).child(16).setText(0, _translate("Form", "syn"))
        self.treeWidget.topLevelItem(5).child(17).setText(0, _translate("Form", "fin"))
        self.treeWidget.topLevelItem(5).child(18).setText(0, _translate("Form", "expert info"))
        self.treeWidget.topLevelItem(5).child(19).setText(0, _translate("Form", "connection finsh"))
        self.treeWidget.topLevelItem(5).child(20).setText(0, _translate("Form", "serveroty level"))
        self.treeWidget.topLevelItem(5).child(21).setText(0, _translate("Form", "group "))
        self.treeWidget.topLevelItem(5).child(22).setText(0, _translate("Form", "tcp flag"))
        self.treeWidget.topLevelItem(5).child(23).setText(0, _translate("Form", "window size"))
        self.treeWidget.topLevelItem(5).child(24).setText(0, _translate("Form", "calculated window"))
        self.treeWidget.topLevelItem(5).child(25).setText(0, _translate("Form", "window size sca;ing factor"))
        self.treeWidget.topLevelItem(5).child(26).setText(0, _translate("Form", "checksum"))
        self.treeWidget.topLevelItem(5).child(27).setText(0, _translate("Form", "checksum status"))
        self.treeWidget.topLevelItem(5).child(28).setText(0, _translate("Form", "urgent pointer"))
        self.treeWidget.topLevelItem(5).child(29).setText(0, _translate("Form", "seq/ack"))
        self.treeWidget.topLevelItem(5).child(30).setText(0, _translate("Form", "irtt"))
        self.treeWidget.topLevelItem(5).child(31).setText(0, _translate("Form", "tcp analysis flags"))
        self.treeWidget.topLevelItem(5).child(32).setText(0, _translate("Form", "expert indo(note/sequence)"))
        self.treeWidget.topLevelItem(5).child(33).setText(0, _translate("Form", "this frame is "))
        self.treeWidget.topLevelItem(5).child(34).setText(0, _translate("Form", "severity level"))
        self.treeWidget.topLevelItem(5).child(35).setText(0, _translate("Form", "group"))
        self.treeWidget.topLevelItem(5).child(36).setText(0, _translate("Form", "the rto for this segemnt was"))
        self.treeWidget.topLevelItem(5).child(37).setText(0, _translate("Form", "RTO basded on delta from frame"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("Form", "udp"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("Form", "source port"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("Form", "destination port"))
        self.treeWidget.topLevelItem(6).child(2).setText(0, _translate("Form", "length"))
        self.treeWidget.topLevelItem(6).child(3).setText(0, _translate("Form", "checksum"))
        self.treeWidget.topLevelItem(6).child(4).setText(0, _translate("Form", "checksum status"))
        self.treeWidget.topLevelItem(6).child(5).setText(0, _translate("Form", "stream index"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("Form", "data"))
        self.treeWidget.topLevelItem(7).child(0).setText(0, _translate("Form", "data"))
        self.treeWidget.topLevelItem(7).child(1).setText(0, _translate("Form", "length"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
    def setmydata(self,index):
        mylock = Threerowsdata.dictL
        mysecandthirddata = Threerowsdata.firstrowdata[index]



import sys
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form()
    ui.show()
    sys.exit(app.exec_())

"""
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newDetailSecondrowdata.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
# 2018/4/8
# version 2
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(784, 754)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_4 = QtWidgets.QTreeWidgetItem(item_3)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "frame"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "1-Interface id"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Form", "Interface name"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "2-Arrival time"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Form", "3-timeshift"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Form", "4-Epoch time"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("Form", "5-time delta from captured frame"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("Form", "6-time delta from displayed frame"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("Form", "7-time since reference or first frame"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("Form", "8-frame number"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("Form", "9-frame length"))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("Form", "11-capture length"))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("Form", "12-frame is marked"))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("Form", "13-frame is ignored"))
        self.treeWidget.topLevelItem(0).child(12).setText(0, _translate("Form", "14-protocol in frame:"))
        self.treeWidget.topLevelItem(0).child(13).setText(0, _translate("Form", "15-color rule name"))
        self.treeWidget.topLevelItem(0).child(14).setText(0, _translate("Form", "16-color rule string"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "ethernet "))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "destination"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("Form", "address (hard device)"))
        self.treeWidget.topLevelItem(1).child(0).child(1).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(0).child(2).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "source "))
        self.treeWidget.topLevelItem(1).child(1).child(0).setText(0, _translate("Form", "address(hard device)"))
        self.treeWidget.topLevelItem(1).child(1).child(1).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(1).child(2).setText(0, _translate("Form", "...."))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Form", "type"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "PPPOE"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Form", "version:"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("Form", "type"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("Form", "session id"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("Form", "payload length"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("Form", "p2p"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("Form", "protocol"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("Form", "ip"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("Form", "version"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("Form", "header length"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("Form", "different service field"))
        self.treeWidget.topLevelItem(4).child(2).child(0).setText(0, _translate("Form", "different services codepoint"))
        self.treeWidget.topLevelItem(4).child(2).child(1).setText(0, _translate("Form", "explicit congestion notification"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("Form", "total length"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("Form", "identification"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("Form", "flags"))
        self.treeWidget.topLevelItem(4).child(5).child(0).setText(0, _translate("Form", "reverse bit"))
        self.treeWidget.topLevelItem(4).child(5).child(1).setText(0, _translate("Form", "dont fragment"))
        self.treeWidget.topLevelItem(4).child(5).child(2).setText(0, _translate("Form", "more fragment"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("Form", "fragment offset"))
        self.treeWidget.topLevelItem(4).child(7).setText(0, _translate("Form", "time to live"))
        self.treeWidget.topLevelItem(4).child(8).setText(0, _translate("Form", "protocol"))
        self.treeWidget.topLevelItem(4).child(9).setText(0, _translate("Form", "header checksum"))
        self.treeWidget.topLevelItem(4).child(10).setText(0, _translate("Form", "header checksum status"))
        self.treeWidget.topLevelItem(4).child(11).setText(0, _translate("Form", "source "))
        self.treeWidget.topLevelItem(4).child(12).setText(0, _translate("Form", "destination"))
        self.treeWidget.topLevelItem(4).child(13).setText(0, _translate("Form", "source geoip"))
        self.treeWidget.topLevelItem(4).child(14).setText(0, _translate("Form", "destinatoin geoip"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("Form", "tcp"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("Form", "source port"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("Form", "destination port"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("Form", "stream index"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("Form", "tcp segment"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("Form", "sequence number"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("Form", "ACK"))
        self.treeWidget.topLevelItem(5).child(6).setText(0, _translate("Form", "header length"))
        self.treeWidget.topLevelItem(5).child(7).setText(0, _translate("Form", "flags"))
        self.treeWidget.topLevelItem(5).child(7).child(0).setText(0, _translate("Form", "reversed"))
        self.treeWidget.topLevelItem(5).child(7).child(1).setText(0, _translate("Form", "nonce"))
        self.treeWidget.topLevelItem(5).child(7).child(2).setText(0, _translate("Form", "congestion"))
        self.treeWidget.topLevelItem(5).child(7).child(3).setText(0, _translate("Form", "ecn echo"))
        self.treeWidget.topLevelItem(5).child(7).child(4).setText(0, _translate("Form", "urgent"))
        self.treeWidget.topLevelItem(5).child(7).child(5).setText(0, _translate("Form", "ack"))
        self.treeWidget.topLevelItem(5).child(7).child(6).setText(0, _translate("Form", "push"))
        self.treeWidget.topLevelItem(5).child(7).child(7).setText(0, _translate("Form", "reset"))
        self.treeWidget.topLevelItem(5).child(7).child(8).setText(0, _translate("Form", "syn"))
        self.treeWidget.topLevelItem(5).child(7).child(9).setText(0, _translate("Form", "fin"))
        self.treeWidget.topLevelItem(5).child(7).child(9).child(0).setText(0, _translate("Form", "expert info"))
        self.treeWidget.topLevelItem(5).child(7).child(9).child(0).child(0).setText(0, _translate("Form", "connection finsh"))
        self.treeWidget.topLevelItem(5).child(7).child(9).child(0).child(1).setText(0, _translate("Form", "serveroty level"))
        self.treeWidget.topLevelItem(5).child(7).child(9).child(0).child(2).setText(0, _translate("Form", "group "))
        self.treeWidget.topLevelItem(5).child(7).child(9).child(1).setText(0, _translate("Form", "tcp flag"))
        self.treeWidget.topLevelItem(5).child(8).setText(0, _translate("Form", "window size"))
        self.treeWidget.topLevelItem(5).child(9).setText(0, _translate("Form", "calculated window"))
        self.treeWidget.topLevelItem(5).child(10).setText(0, _translate("Form", "window size sca;ing factor"))
        self.treeWidget.topLevelItem(5).child(11).setText(0, _translate("Form", "checksum"))
        self.treeWidget.topLevelItem(5).child(12).setText(0, _translate("Form", "checksum status"))
        self.treeWidget.topLevelItem(5).child(13).setText(0, _translate("Form", "urgent pointer"))
        self.treeWidget.topLevelItem(5).child(14).setText(0, _translate("Form", "seq/ack"))
        self.treeWidget.topLevelItem(5).child(14).child(0).setText(0, _translate("Form", "irtt"))
        self.treeWidget.topLevelItem(5).child(14).child(1).setText(0, _translate("Form", "tcp analysis flags"))
        self.treeWidget.topLevelItem(5).child(14).child(1).child(0).setText(0, _translate("Form", "expert indo(note/sequence)"))
        self.treeWidget.topLevelItem(5).child(14).child(1).child(0).child(0).setText(0, _translate("Form", "this frame is "))
        self.treeWidget.topLevelItem(5).child(14).child(1).child(0).child(1).setText(0, _translate("Form", "severity level"))
        self.treeWidget.topLevelItem(5).child(14).child(1).child(0).child(2).setText(0, _translate("Form", "group"))
        self.treeWidget.topLevelItem(5).child(14).child(1).child(1).setText(0, _translate("Form", "the rto for this segemnt was"))
        self.treeWidget.topLevelItem(5).child(14).child(1).child(2).setText(0, _translate("Form", "RTO basded on delta from frame"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("Form", "udp"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("Form", "source port"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("Form", "destination port"))
        self.treeWidget.topLevelItem(6).child(2).setText(0, _translate("Form", "length"))
        self.treeWidget.topLevelItem(6).child(3).setText(0, _translate("Form", "checksum"))
        self.treeWidget.topLevelItem(6).child(4).setText(0, _translate("Form", "checksum status"))
        self.treeWidget.topLevelItem(6).child(5).setText(0, _translate("Form", "stream index"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("Form", "data"))
        self.treeWidget.topLevelItem(7).child(0).setText(0, _translate("Form", "data"))
        self.treeWidget.topLevelItem(7).child(1).setText(0, _translate("Form", "length"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
    def 

import sys
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""